#!/bin/bash

. "$EUPS_DIR/lib/eupspkg.sh"

build()
{
    default_build

    cd python
    python setup.py build
}

install()
{
    default_install

    PYDEST="$PREFIX/lib/python"
    mkdir -p "$PYDEST"
    cd python
    PYTHONPATH="$PYDEST:$PYTHONPATH" python setup.py install $PYSETUP_INSTALL_OPTIONS
}

"$@"
